import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CustomRainbowKitProvider } from '@/config/rainbowkit-config'
import { StarsCanvas } from '@/components/stars-background'
import { Navbar } from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#030014] overflow-hidden h-full w-full`}>
        <CustomRainbowKitProvider>
          <StarsCanvas />
          <Navbar />
          {children}
        </CustomRainbowKitProvider>
        <Toaster />
      </body>
    </html>
  )
}
